dist: trusty

language: c

addons:
  apt:
    sources:
    - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
    - gcc-arm-embedded

script:
    - make core-module-release OUT=bcf-gateway-core-module-${TRAVIS_TAG} VERSION=${TRAVIS_TAG}
    - make usb-dongle-release OUT=bcf-gateway-usb-dongle-${TRAVIS_TAG} VERSION=${TRAVIS_TAG}

deploy:
    skip_cleanup: true
    file_glob: true
    file: "out/release/*.bin"
    api_key: "${GITHUB_KEY}"
    provider: releases
    overwrite: true
    on:
       tags: true
